version: "3.7"

services:
  app:
    container_name: app-container
    restart: always
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo-container
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
volumes:
   mongodb: