DROP TABLE IF EXISTS PRODUCT_CAST;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS STUDIO;
DROP TABLE IF EXISTS RATING;
DROP TABLE IF EXISTS FORMAT;

CREATE TABLE RATING (
  RATING_ID SERIAL PRIMARY KEY,
  RATING_NAME VARCHAR(5) NOT NULL UNIQUE
);

CREATE TABLE FORMAT (
  FORMAT_ID SERIAL PRIMARY KEY,
  FORMAT_NAME VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE STUDIO (
  STUDIO_ID SERIAL PRIMARY KEY,
  STUDIO_NAME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE PRODUCT (
  PRODUCT_ID SERIAL PRIMARY KEY,
  ASPECT_RATIO VARCHAR(255),
  RATING_ID INT REFERENCES RATING(RATING_ID),
  DIMENSIONS VARCHAR(255),
  FORMAT_ID INT REFERENCES FORMAT(FORMAT_ID),
  RUNTIME VARCHAR(255),
  RELEASE_DATE DATE,
  NUMBER_OF_DISKS INT,
  CAST_LIST TEXT,
  STUDIO_ID INT REFERENCES STUDIO(STUDIO_ID)
);

CREATE TABLE PRODUCT_CAST (
  PRODUCT_ID INT REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,
  CAST_NAME VARCHAR(255)
);